<?php
/**
 * VirusScanAdvancedResultTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * virusapi
 *
 * The Cloudmersive Virus Scan API lets you scan files and content for viruses and identify security issues with content.
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.3.1
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * VirusScanAdvancedResultTest Class Doc Comment
 *
 * @category    Class */
// * @description Result of running an advanced virus scan
/**
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class VirusScanAdvancedResultTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "VirusScanAdvancedResult"
     */
    public function testVirusScanAdvancedResult()
    {
    }

    /**
     * Test attribute "clean_result"
     */
    public function testPropertyCleanResult()
    {
    }

    /**
     * Test attribute "contains_executable"
     */
    public function testPropertyContainsExecutable()
    {
    }

    /**
     * Test attribute "contains_invalid_file"
     */
    public function testPropertyContainsInvalidFile()
    {
    }

    /**
     * Test attribute "contains_script"
     */
    public function testPropertyContainsScript()
    {
    }

    /**
     * Test attribute "contains_password_protected_file"
     */
    public function testPropertyContainsPasswordProtectedFile()
    {
    }

    /**
     * Test attribute "contains_restricted_file_format"
     */
    public function testPropertyContainsRestrictedFileFormat()
    {
    }

    /**
     * Test attribute "verified_file_format"
     */
    public function testPropertyVerifiedFileFormat()
    {
    }

    /**
     * Test attribute "found_viruses"
     */
    public function testPropertyFoundViruses()
    {
    }
}
