<?php
/**
 * ScanCloudStorageApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * virusapi
 *
 * The Cloudmersive Virus Scan API lets you scan files and content for viruses and identify security issues with content.
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.3.1
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Client;

use \Swagger\Client\Configuration;
use \Swagger\Client\ApiException;
use \Swagger\Client\ObjectSerializer;

/**
 * ScanCloudStorageApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class ScanCloudStorageApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for scanCloudStorageScanAwsS3File
     *
     * Scan an AWS S3 file for viruses.
     *
     */
    public function testScanCloudStorageScanAwsS3File()
    {
    }

    /**
     * Test case for scanCloudStorageScanAzureBlob
     *
     * Scan an Azure Blob for viruses.
     *
     */
    public function testScanCloudStorageScanAzureBlob()
    {
    }

    /**
     * Test case for scanCloudStorageScanGcpStorageFile
     *
     * Scan an Google Cloud Platform (GCP) Storage file for viruses.
     *
     */
    public function testScanCloudStorageScanGcpStorageFile()
    {
    }
}
